/* DSblock model generated by Dymola from Modelica model Modelica.Electrical.Analog.Examples.ChuaCircuit
 Dymola Version 2015 FD01 (64-bit), 2014-11-04 translated this at Fri Dec 19 12:35:58 2014

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Modelica.Electrical.Analog.Examples.ChuaCircuit";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/u0098668/appdata/roaming/dynasim/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
W_[3] = false;
W_[9] = false;
W_[2] = 0;
W_[14] = 0.0;
W_[16] = 0.0;
W_[19] = 0.0;
W_[18] = 0.0;
BoundParameterSection
W_[4] = DP_[2];
AssertModelica(1+DP_[3]*(W_[4]-DP_[2]) >= 1E-015,"1+Ro.alpha*(Ro.T-Ro.T_ref) >= 1E-015",
   "Temperature outside scope of model!");
W_[10] = DP_[5];
AssertModelica(1+DP_[6]*(W_[10]-DP_[5]) >= 1E-015,"1+G.alpha*(G.T-G.T_ref) >= 1E-015",
   "Temperature outside scope of model!");
W_[12] = divmacro(DP_[4],"G.G",1+DP_[6]*(W_[10]-DP_[5]),"1+G.alpha*(G.T-G.T_ref)");
W_[6] = DP_[1]*(1+DP_[3]*(W_[4]-DP_[2]));
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection
Init=false;InitializeData(2);Init=true;
EndInitialSection

OutputSection

DynamicsSection
W_[7] = X_[2]-X_[1];
W_[8] = W_[12]*W_[7];
W_[17] = IF Less(X_[1],"C1.v",  -DP_[11]," -Nr.Ve", 0) THEN DP_[10]*(X_[1]+
  DP_[11])-DP_[9]*DP_[11] ELSE IF Greater(X_[1],"C1.v", DP_[11],"Nr.Ve", 1)
   THEN DP_[10]*(X_[1]-DP_[11])+DP_[9]*DP_[11] ELSE DP_[9]*X_[1];
W_[13] = W_[8]-W_[17];
 /* Linear system of equations to solve. */
F_[1] = RememberSimple_(F_[1], 0);
SolveScalarLinearParametric( -DP_[7]," -C1.C",  -W_[13]," -C1.i", F_[1],
  "der(C1.v)");
 /* End of Equation Block */ 

W_[15] =  -(W_[8]+X_[0]);
 /* Linear system of equations to solve. */
F_[2] = RememberSimple_(F_[2], 1);
SolveScalarLinearParametric( -DP_[8]," -C2.C",  -W_[15]," -C2.i", F_[2],
  "der(C2.v)");
 /* End of Equation Block */ 

W_[1] = W_[6]*X_[0];
W_[0] = X_[2]-W_[1];
 /* Linear system of equations to solve. */
F_[0] = RememberSimple_(F_[0], 2);
SolveScalarLinearParametric(DP_[0],"L.L", W_[0],"L.v", F_[0],"der(L.i)");
 /* End of Equation Block */ 


AcceptedSection1

AcceptedSection2
W_[5] = W_[1]*X_[0];
W_[11] = W_[7]*W_[8];
W_[20] = W_[13]+W_[15]+W_[17]+X_[0];

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("L.v", "Voltage drop between the two pins (= p.v - n.v) [V]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareState("L.i", "Current flowing from pin p to pin n [A]", 0, 0, 0.0,0.0,0.0,\
0,560)
DeclareDerivative("L.der(i)", "der(Current flowing from pin p to pin n) [A/s]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("L.p.v", "Potential at the pin [V]", "C2.v", 1, 1, 2, 4)
DeclareAlias2("L.p.i", "Current flowing into the pin [A]", "L.i", 1, 1, 0, 132)
DeclareVariable("L.n.v", "Potential at the pin [V]", 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("L.n.i", "Current flowing into the pin [A]", "L.i", -1, 1, 0, 132)
DeclareParameter("L.L", "Inductance [H]", 0, 18, 0.0,0.0,0.0,0,560)
DeclareParameter("Ro.R", "Resistance at temperature T_ref [Ohm]", 1, 0.0125, \
0.0,0.0,0.0,0,560)
DeclareParameter("Ro.T_ref", "Reference temperature [K|degC]", 2, 300.15, 0.0,\
1E+100,300.0,0,560)
DeclareParameter("Ro.alpha", "Temperature coefficient of resistance (R_actual = R*(1 + alpha*(T_heatPort - T_ref)) [1/K]",\
 3, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("Ro.v", "Voltage drop between the two pins (= p.v - n.v) [V]", \
"L.n.v", 1, 5, 1, 0)
DeclareAlias2("Ro.i", "Current flowing from pin p to pin n [A]", "L.i", 1, 1, 0,\
 0)
DeclareAlias2("Ro.p.v", "Potential at the pin [V]", "L.n.v", 1, 5, 1, 4)
DeclareAlias2("Ro.p.i", "Current flowing into the pin [A]", "L.i", 1, 1, 0, 132)
DeclareVariable("Ro.n.v", "Potential at the pin [V]", 0, 0.0,0.0,0.0,0,521)
DeclareAlias2("Ro.n.i", "Current flowing into the pin [A]", "L.i", -1, 1, 0, 132)
DeclareVariable("Ro.useHeatPort", "=true, if HeatPort is enabled [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("Ro.T", "Fixed device temperature if useHeatPort = false [K|degC]",\
 288.15, 0.0,1E+100,300.0,0,513)
DeclareVariable("Ro.LossPower", "Loss power leaving component via HeatPort [W]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("Ro.T_heatPort", "Temperature of HeatPort [K|degC]", "Ro.T", 1, 5,\
 4, 0)
DeclareVariable("Ro.R_actual", "Actual resistance = R*(1 + alpha*(T_heatPort - T_ref)) [Ohm]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("G.G", "Conductance at temperature T_ref [S]", 4, 0.565, \
0.0,0.0,0.0,0,560)
DeclareParameter("G.T_ref", "Reference temperature [K|degC]", 5, 300.15, 0.0,\
1E+100,300.0,0,560)
DeclareParameter("G.alpha", "Temperature coefficient of conductance (G_actual = G_ref/(1 + alpha*(T_heatPort - T_ref)) [1/K]",\
 6, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("G.v", "Voltage drop between the two pins (= p.v - n.v) [V]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("G.i", "Current flowing from pin p to pin n [A]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("G.p.v", "Potential at the pin [V]", "C2.v", 1, 1, 2, 4)
DeclareAlias2("G.p.i", "Current flowing into the pin [A]", "G.i", 1, 5, 8, 132)
DeclareAlias2("G.n.v", "Potential at the pin [V]", "C1.v", 1, 1, 1, 4)
DeclareAlias2("G.n.i", "Current flowing into the pin [A]", "G.i", -1, 5, 8, 132)
DeclareVariable("G.useHeatPort", "=true, if HeatPort is enabled [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("G.T", "Fixed device temperature if useHeatPort = false [K|degC]",\
 288.15, 0.0,1E+100,300.0,0,513)
DeclareVariable("G.LossPower", "Loss power leaving component via HeatPort [W]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("G.T_heatPort", "Temperature of HeatPort [K|degC]", "G.T", 1, 5, 10,\
 0)
DeclareVariable("G.G_actual", "Actual conductance = G_ref/(1 + alpha*(T_heatPort - T_ref)) [S]",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareState("C1.v", "Voltage drop between the two pins (= p.v - n.v) [V]", 1, 4,\
 0.0,0.0,0.0,0,560)
DeclareDerivative("C1.der(v)", "der(Voltage drop between the two pins (= p.v - n.v)) [V/s]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("C1.i", "Current flowing from pin p to pin n [A]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("C1.p.v", "Potential at the pin [V]", "C1.v", 1, 1, 1, 4)
DeclareAlias2("C1.p.i", "Current flowing into the pin [A]", "C1.i", 1, 5, 13, 132)
DeclareVariable("C1.n.v", "Potential at the pin [V]", 0.0, 0.0,0.0,0.0,0,521)
DeclareAlias2("C1.n.i", "Current flowing into the pin [A]", "C1.i", -1, 5, 13, 132)
DeclareParameter("C1.C", "Capacitance [F]", 7, 10, 0.0,1E+100,0.0,0,560)
DeclareState("C2.v", "Voltage drop between the two pins (= p.v - n.v) [V]", 2, 0,\
 0.0,0.0,0.0,0,560)
DeclareDerivative("C2.der(v)", "der(Voltage drop between the two pins (= p.v - n.v)) [V/s]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("C2.i", "Current flowing from pin p to pin n [A]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("C2.p.v", "Potential at the pin [V]", "C2.v", 1, 1, 2, 4)
DeclareAlias2("C2.p.i", "Current flowing into the pin [A]", "C2.i", 1, 5, 15, 132)
DeclareVariable("C2.n.v", "Potential at the pin [V]", 0.0, 0.0,0.0,0.0,0,521)
DeclareAlias2("C2.n.i", "Current flowing into the pin [A]", "C2.i", -1, 5, 15, 132)
DeclareParameter("C2.C", "Capacitance [F]", 8, 100, 0.0,1E+100,0.0,0,560)
DeclareAlias2("Nr.v", "Voltage drop between the two pins (= p.v - n.v) [V]", \
"C1.v", 1, 1, 1, 0)
DeclareVariable("Nr.i", "Current flowing from pin p to pin n [A]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("Nr.p.v", "Potential at the pin [V]", "C1.v", 1, 1, 1, 4)
DeclareAlias2("Nr.p.i", "Current flowing into the pin [A]", "Nr.i", 1, 5, 17, 132)
DeclareVariable("Nr.n.v", "Potential at the pin [V]", 0.0, 0.0,0.0,0.0,0,521)
DeclareAlias2("Nr.n.i", "Current flowing into the pin [A]", "Nr.i", -1, 5, 17, 132)
DeclareParameter("Nr.Ga", "Conductance in inner voltage range [S]", 9, -0.757576,\
 -1.0,1E+100,0.0,0,560)
DeclareParameter("Nr.Gb", "Conductance in outer voltage range [S]", 10, \
-0.409091, -1.0,1E+100,0.0,0,560)
DeclareParameter("Nr.Ve", "Inner voltage range limit [V]", 11, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("Gnd.p.v", "Potential at the pin [V]", 0.0, 0.0,0.0,0.0,0,521)
DeclareVariable("Gnd.p.i", "Current flowing into the pin [A]", 0.0, 0.0,0.0,0.0,\
0,776)
EndNonAlias(0)
#define NX_    3
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    21
#define NP_    12
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -1205820306
#define NHash2_ 238141135
#define NHash3_ 0
#define NI_    0
#define NRelF_ 2
#define NRel_  2
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    24
#define SizePre_ 0
#define SizeEq_ 3
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
StartEqBlock
DoRemember_(F_[1], 0.0, 0);
DoRemember_(F_[2], 0.0, 1);
DoRemember_(F_[0], 0.0, 2);
EndEqBlock
EndDataBlock
